Blog/Blog/urls.py
from django.contrib import admin
from django.urls import path ,include
from . import settings #we use setting model in setting.py , so we import it
from django.conf.urls.static import static # to use setting media root and urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
    path('index/', include("index.urls")),
    path('accounts/',include("accounts.urls")),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Blog/blog_op/urls.py
from django.urls import path
from .import views

app_name = 'blog_op'

urlpatterns =[
    path('add/',views.add_blog,name='add_blog'),
    path('publications/',views.publications,name='publications'),
    path('puplidhed/<published_id>/',views.published_detail,name='published_detail'),
    path('update/<published_id>/',views.update,name='update'),
    path('delete/<published_id>/',views.delete_blog,name='delete_blog'),
    path("search/",views.search,name='search')
]

Blog/blog_op/models.py
from typing import Any
from django.db import models

# Create your models here.

class Published(models.Model):
    blogs_content = models.TextChoices("blogs_content",['News',"Story","Poetry"])
    title = models.CharField(max_length=255)
    content = models.TextField()
    is_published = models.BooleanField()
    published_at = models.DateField()
    blog_content =models.CharField(max_length=56,choices = blogs_content.choices, default="Story")
    image = models.ImageField(upload_to="images/",default="images/default.jpg")
    

Blog/blog_op/views.py
from django.shortcuts import render ,redirect
from django.http import HttpRequest
from .models import Published
# Create your views here.

def add_blog(request:HttpRequest):
    
    if request.method == 'POST':
        
        try:
            new_published = Published(title=request.POST['title'],content =request.POST['content'],is_published=request.POST['is_published'],published_at=request.POST['published_at'],image = request.FILES["image"],blog_content=request.POST["blog_content"])
            
            new_published.save()
        except Exception:
            return redirect('blog_op:add_blog')
    
        return redirect('blog_op:publications')

    return render (request,'blog_op/add.html',{"blog_content": Published.blogs_content})

def publications(request:HttpRequest):

   
    
    if 'search' in request.GET:
        search_value = request.GET['search']
        pub = Published.objects.filter(blog_content=search_value)
    else: pub = Published.objects.all()
    
    return render(request,'blog_op/publications.html',{'publications':pub,"blog_content": Published.blogs_content})



def published_detail(request:HttpRequest,published_id):
    try:
        publidhed = Published.objects.get(id=published_id)
        return render(request,'blog_op/detail.html',{'puplidhed':publidhed})
    except  Exception:
        return redirect('blog_op:publications')


def update(request:HttpRequest,published_id):
    published = Published.objects.get(id=published_id)
    if request.method == 'POST':
        published.title = request.POST["title"]
        published.content =request.POST['content']
        published.published_at=request.POST['published_at']
        published.blog_content = request.POST['blog_content']
        published.image = request.FILES["image"]
        published.save()
        redirect('blog_op:publications')
        
    return render(request,'blog_op/update.html',{'update':published,"blog_content": Published.blogs_content})



def delete_blog(request:HttpRequest,published_id):
    
    published = Published.objects.get(id=published_id)
    published.delete()
    
    return redirect('blog_op:publications')


def search(request:HttpRequest):
    if "search" in request.GET:
        search_value = request.GET['search']
        pup =Published.objects.filter(title__contains=search_value)
    else:
        pup = Published.objects.all() 
    return render(request,"blog_op/search.html",{'search':pup})

Blog/blog_op/templates/blog_op/add.html
{% extends 'main/base.html' %}

{% load static %}

{% block title %}Add Blog{% endblock %}

{% block content %}

<div class="container">
    <h1>Add Blog Post</h1>

    <form method="POST" action="{% url 'blog_op:add_blog' %}" enctype="multipart/form-data">
        {% csrf_token %}
      <div class="mb-3">
        <label for="title" class="form-label">Title</label>
        <input type="text" class="form-control"  name="title" required>
      </div>

      <div class="mb-3">
        <label for="content" class="form-label">Content</label>
        <textarea class="form-control"name="content" rows="3" ></textarea>
      </div>
      <div class="mb-3">
        <label for="formFile" class="form-label">Add image</label>
        <input class="form-control" name="image" type="file" id="formFile">
      </div>
      {% for key , value in blog_content.choices %}
        <div class="form-check">
          <input class="form-check-input" type="radio" name="blog_content" value="{{value}}" id="{{key}}">
          <label>
            {{value}}
          </label>
        </div>
      {% endfor %}

      <div class="mb-3">
        <label for="date" class="form-label">Date</label>
        <input type="date" class="form-control"  name="published_at" >
      </div>
      <div class="mb-3">
        <label for="date" class="form-label">do you want published?</label>
        <input type="checkbox"   name="is_published" value="True">

      </div>

      <button type="submit" class="btn btn-primary">Post</button>
    </form>
  </div>

{% endblock %}

Blog/blog_op/templates/blog_op/detail.html
{% extends 'main/base.html' %}

{% load static %}

{% block title %}published detail{% endblock %}

{% block content %}

<div class="container" >
    <div class="row">

        <div class="col">
            <div class="blog-post">
                <img style="width: 30%;" src="{{puplidhed.image.url}}" alt="">
                <h2 class="blog-post-title">{{puplidhed.title}}</h2>

                <img src="{{p.image.url}}" alt="">
                <p>{{puplidhed.content}}</p>
          
              </div>
            
        </div>

    </div>
</div>

{% endblock %}

Blog/blog_op/templates/blog_op/publications.html
{% extends 'main/base.html' %}

{% load static %}

{% block title %}Publications{% endblock %}

{% block content %}

<div class="container" >
    <div class="row">
        
        <div class="col-10">
            {% for p in publications %}
            <div class="blog-post d-flex justify-content-between">
                <div>
                  <h1 class="bg-dark-subtle" >{{p.blog_content}}</h1>
                  <img style="width: 30%;" src="{{p.image.url}}" alt="">
                <a href="{% url 'blog_op:published_detail' p.id %}"><h2 class="blog-post-title">{{p.title}}</h2></a>
                <p class="blog-post-meta">posted on:{{p.published_at}}</p>
                <p>{{p.content}}</p>
                </div>
                <div>
                    <div class="dropdown">
                        <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                          Action
                        </button>
                        <ul class="dropdown-menu">
                          <li><a class="dropdown-item" href="{% url 'blog_op:update' p.id %}">update</a></li>
                          <li><a class="dropdown-item" href="{% url 'blog_op:delete_blog' p.id %}">delete</a></li>
                         
                        </ul>
                      </div>
                </div>
                
              </div>
              <hr class="border border-primary border-3 opacity-75">
            {% endfor %}
        </div>
        <div class="col-2" >
          <div class="position-sticky top-50 end-0 translate-middle-y" >
            <div class="d-flex flex-column mb-3">
              <a style="width: 100%; text-decoration: none;" class="border-20 border bg-primary text-white p-3 text-center"  href="{% url 'blog_op:publications'%}">All</a>
                {% for key , value in blog_content.choices %}
                  <a style="width: 100%; text-decoration: none;" class="border-20 border bg-primary text-white p-3 text-center"  href="{% url 'blog_op:publications'%}?search={{key}}">{{value}}</a>  
                {% endfor %}
            </div>
          </div>
        </div>

    </div>
</div>

{% endblock %}

Blog/blog_op/templates/blog_op/search.html
{% extends 'main/base.html' %}

{% load static %}

{% block title %}search{% endblock %}

{% block content %}

<div class="container" >
    <div class="row">
        <div class="col-10">
            <h1> result of {{ request.GET.search }}</h1>
            {% for p in search %}
            <div class="blog-post d-flex justify-content-between">
                <div>
                  <h1 class="bg-dark-subtle" >{{p.blog_content}}</h1>
                  <img style="width: 30%;" src="{{p.image.url}}" alt="">
                <a href="{% url 'blog_op:published_detail' p.id %}"><h2 class="blog-post-title">{{p.title}}</h2></a>
                <p class="blog-post-meta">posted on:{{p.published_at}}</p>
                <p>{{p.content}}</p>
                </div>
                <div>
                    <div class="dropdown">
                        <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                          Action
                        </button>
                        <ul class="dropdown-menu">
                          <li><a class="dropdown-item" href="{% url 'blog_op:update' p.id %}">update</a></li>
                          <li><a class="dropdown-item" href="{% url 'blog_op:delete_blog' p.id %}">delete</a></li>
                         
                        </ul>
                      </div>
                </div>
                
              </div>
              <hr class="border border-primary border-3 opacity-75">
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

Blog/blog_op/templates/blog_op/update.html
{% extends 'main/base.html' %}

{% load static %}

{% block title %}Update Blog{% endblock %}

{% block content %}

<div class="container">
    <h1>update {{update.title}}</h1>

    <form method="POST" action="{% url 'blog_op:update' update.id %}" enctype="multipart/form-data">
        {% csrf_token %}
      <div class="mb-3">
        <label for="title" class="form-label">Title</label>
        <input type="text" class="form-control" value="{{update.title}}" name="title" >
      </div>

      <div class="mb-3">
        <label for="content" class="form-label">Content</label>
        <textarea class="form-control"name="content"  rows="3" >{{update.content}}</textarea>
      </div>
      <div class="mb-3">
        <label for="formFile" class="form-label">Add image</label>
        <input class="form-control"  name="image" type="file" id="formFile">
      </div>
      {% for key , value in blog_content.choices %}
      <div class="form-check">
        <input class="form-check-input" type="radio" name="blog_content" value="{{value}}" id="{{key}}">
        <label>
          {{value}}
        </label>
      </div>
    {% endfor %}
      <div class="mb-3">
        <label for="date" class="form-label">Date</label>
        <input type="date" class="form-control" value="{{update.published_at|date:'Y-m-d' }}"  name="published_at" >
      </div>

      <button type="submit" class="btn btn-primary">Post</button>
    </form>
  </div>

{% endblock %}