BlogWeb/Blog/urls.py
from django.urls import path
from . import views
app_name = "Blog"
urlpatterns = [
    path('read/',views.read_blog,name='read_blog'),
    path('add/',views.add_blog,name='add_blog'),
    path('detail/<blog_id>/',views.blog_detail,name='blog_detail'),
    path('doesnotexist/',views.not_exist,name='not_exist'),
    path('update/<blog_id>/',views.update_blog,name='update_blog'),
    path('delete/<blog_id>/',views.delete_blog,name='delete_blog'),
    path('search/',views.search_page,name='search_page'),
    path('category/<cat>/',views.category_blog,name='category_blog') 
]

BlogWeb/BlogWeb/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
     path('blogs/', include("blog.urls")),
    ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BlogWeb/blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [ 
    path("add/",views.add_blog_views, name="add_blog_views"),
    path("", views.home_blog_views, name="home_blog_views"),
    path("details/<blog_id>/", views.details_blog_views, name="details_blog_views"),
    path("updated/<blog_id>/", views.updated_blog, name="updated_blog"),
    path("delete/<blog_id>/", views.delete_blog_views ,name="delete_blog_views"),
    path('search/', views.search_blog_views, name="search_blog_views")
   # path('category/<item>',views.home_views_category,name="home_views_category")
]

BlogWeb/main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [ 
    path("",views.home_views, name="home_views")
    # path("add/", views.add_movie_view, name="add_movie_view"),
    # path("", views.movies_home_view, name="movie_home_view")

]

BlogWeb/Blog/models.py
from django.db import models
 

class Blog1(models.Model):
    categories=models.TextChoices('categories',['Food','Travel','Fashion','Personal'])
    title=models.CharField(max_length=2000)
    content=models.TextField()
    is_published=models.BooleanField()
    published_at=models.DateField()
    category=models.CharField(max_length=200,choices=categories.choices)
    image= models.ImageField(upload_to="images/", default="images/blog.jpeg")
        # Create your models here.

BlogWeb/blog/models.py
from django.db import models

# Create your models here.
class Blog(models.Model):
    categories=models.TextChoices("categories",["Travel", "Art","Food"])
    title =models.CharField(max_length=256, default="")
    content= models.TextField(default="")
    is_published =models.BooleanField(default=False)
    published_at =models.DateTimeField(null=True , blank=True)
    category=models.CharField(max_length=156,choices=categories.choices, default="")
    image = models.ImageField(upload_to="img/", default="img/default.png")

BlogWeb/Blog/views.py
from django.shortcuts import render,redirect
from django.http import HttpRequest, HttpResponse
from .models import Blog1
# Create your views here.

def read_blog(request : HttpRequest):
    blogs=Blog1.objects.all()
    return render(request, "Blog/read_blog.html", {"blogs" : blogs})

def add_blog(request : HttpRequest):
    if request.method=="POST":
        new_blog=Blog1(title=request.POST['title'],content=request.POST['content'],is_published=request.POST['is_published'],published_at=request.POST['published_at'],category=request.POST['category'],image=request.FILES['image'])
        new_blog.save()
        return redirect("Blog:read_blog")
    return render(request,'Blog/add_blog.html',{"categories" : Blog1.categories})

def blog_detail(request : HttpRequest,blog_id):
    try:
        blog=Blog1.objects.get(id=blog_id)
    except Exception as e :
        return render(request,'Blog/not_exist.html')
    return render(request,'Blog/blog_detail.html',{'blog':blog})


def not_exist(request : HttpRequest):
    return render(request,'Blog/not_exist.html')

def update_blog(request : HttpRequest,blog_id):
    blog=Blog1.objects.get(id=blog_id)
    if request.method=="POST":
        blog.title=request.POST['title']
        blog.content=request.POST['content']
        blog.is_published=request.POST['is_published']
        blog.published_at=request.POST['published_at']
        blog.category=request.POST['category']
        blog.image=request.FILES['image']
        blog.save()
        return redirect('Blog:blog_detail',blog_id=blog.id)
    return render(request,'Blog/update_blog.html',{"blog" : blog,'categories':Blog1.categories})

def delete_blog(request: HttpRequest, blog_id):
    blog = Blog1.objects.get(id=blog_id)
    blog.delete()

    return redirect("Blog:read_blog")

def search_page(request: HttpRequest):
    
    if 'search' in request.GET:
        search_term = request.GET['search']
        blogs = Blog1.objects.filter(title__contains=search_term)
    else:
        blogs = Blog1.objects.all()
    return render(request,'Blog/search_page.html',{'blogs':blogs})

def category_blog(request: HttpRequest,cat):
    blogs=Blog1.objects.filter(category=cat).order_by('published_at')
    return render(request,'Blog/search_page.html',{'blogs':blogs})

BlogWeb/blog/views.py
from django.shortcuts import render , redirect
from django.http import HttpRequest, HttpResponse
from .models import Blog
from django.utils import timezone
# Create your views here.



def add_blog_views(request: HttpRequest):
    if request.method == "POST":
        new_blog = Blog(title=request.POST["title"],content=request.POST["content"],is_published=request.POST["is_published"],category=request.POST["category"],published_at=timezone.now())
        if "image" in request.FILES:
            new_blog.image=request.FILES["image"]
        new_blog.save()
        return redirect("blog:home_blog_views")

    return render(request, "blog/add_blog.html",{"categories":Blog.categories})



def home_blog_views(request: HttpRequest):
    if "category" in request.GET :
        blog =Blog.objects.filter(category=request.GET["category"])
    else:
        blog =Blog.objects.all()

    return render(request, "blog/home_blog.html", {"blogs":blog})

def details_blog_views(request: HttpRequest,blog_id):
        try:
            blogs=Blog.objects.get(id=blog_id)
           
        except:
            return render(request, "blog/page_not_found.html")
         
        return render(request,"blog/details_blog.html",{"blogs":blogs})
             
def updated_blog(request:HttpRequest, blog_id):
    blogs= Blog.objects.get(id=blog_id)

    if request.method == "POST":
        blogs.title = request.POST["title"]
        blogs.content = request.POST["content"]
        blogs.is_published = request.POST["is_published"]
        blogs.published_at=timezone.now()
        blogs.category=request.POST["category"]
        blogs.save()

        return redirect('blog:details_blog_views', blog_id=blogs.id)
     
    return render(request,"blog/updated_blog.html",{"blogs":blogs ,"categories":Blog.categories})

def delete_blog_views (request:HttpRequest, blog_id):
    blogs= Blog.objects.get(id=blog_id)
    blogs.delete()

    return redirect( "blog:home_blog_views")

def search_blog_views(request:HttpRequest):
    if "search" in request.GET:
        return_search=request.GET["search"]
        blog=Blog.objects.filter(title__contains=return_search)
    else:
        blog = Blog.objects.all()

    return render(request, "blog/search.html",{"blogs":blog})

# def home_views_category(request:HttpRequest,item):
    
#     blog= Blog.objects.filter(category=item)
    
#     return render(request, "blog/home_blog.html", {"blogs":blog})

BlogWeb/main/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpRequest, HttpResponse


def home_views(request:HttpRequest):
    return render(request,"main/home.html")

BlogWeb/blog/templates/blog/add_blog.html
{% extends 'main/base.html' %}

{% block contant %}

<div class="container-add">
    <h1> Add New Post , let's go</h1>
    <br>
    <div class="row">
        <div class="col-8">
            <form action="{% url 'blog:add_blog_views' %}"method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <label>Title blog: </label>
                <input  class="form-control" type="text" name="title" placeholder="Enter bolg title ">
            <br>
            <label>Content: </label>
            <textarea name="content"></textarea>
            <br>
            <br>
            <label>is published </label>
            <select name="is_published"  class="form-control">
                <option value="True"> yes</option>
                <option value="False"> no</option>
            </select>
           <br> 
           <label>Category</label>
           {% for key , value in categories.choices %}
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="category" id="{{key}}" value="{{value}}">
                    <label class="form-check-label" for="{{key}}">
                       {{value}}
                    </label>
                </div>
            {% endfor %}

            <label>Plog Poster:</label>
                <input type="file" name="image"  class="form-control" accept="image/*"/>
                
          

            <button  class="form-control" type="submit">submit </button>


            </form>

        </div>
    </div>
</div>
   
   
{%endblock%}

BlogWeb/blog/templates/blog/comment.html
<!-- "way path to use category in base page"
    <ul class="dropdown-menu">
                <li><a name="category" class="dropdown-item" href="{%url 'blog:home_views_category' 'Travel'%}">Travel</a></li>
                <li><a name="category" class="dropdown-item" href="{%url 'blog:home_views_category' 'Art'%}" >Art</a></li>
                <li><a name="category" class="dropdown-item" href="{%url 'blog:home_views_category' 'Food'%}">Food</a></li>
              </ul>-->

BlogWeb/blog/templates/blog/details_blog.html
{% extends 'main/base.html' %}

{% block contant %}

<div class="detalis-contauner">
    <div class="row">
        <div class="col-5">
            <h3>{{blogs.title}}</h3>
            <img width="500px" height="200px"  src="{{blogs.image.url}}" />
            <h3>{{blogs.content}}</h3>
            <h3>{{blogs.is_published}}</h3>
            <h3>{{blogs.published_at}}</h3>



        </div>

    </div>
    <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            Edit Post
        </button>
        <ul class="dropdown-menu dropdown-menu-dark">
          <li><a class="dropdown-item active" href="{% url 'blog:updated_blog' blogs.id %}">Update</a></li>
          <li><a class="dropdown-item" href="{% url 'blog:delete_blog_views' blogs.id %}">Delete</a></li>
        </ul>
      </div>
</div>




{%endblock%}

BlogWeb/blog/templates/blog/home_blog.html
{% extends 'main/base.html' %}

{% block contant %}

<div class="container-home-add">

    <h1>ALL POST</h1>

    <div class="row">

        {% for blog in blogs %}

            <div class="col-5">
                <div class="d-flex flex-column gap-2 p-3 border border-1 rounded-4 shadow mb-4 text-bg-secondary p-3">

                    <a href="{% url 'blog:details_blog_views' blog.id %}"><h3>{{ blog.title }}</h3></a> 
                    <img width="500px" height="200px"  src="{{blog.image.url}}" />
                    <h4>{{blog.content}}</h4>
                    <h4> is published :{{ blog.is_published }} </h4>
                    <h4>  "{{blog.category}}"</h4>
                    <h4>published at {{blog.published_at}}</h4>
                   
                    
                    

                </div>
            </div>
            


        {% endfor %}

    </div>

</div>


{%endblock%}

BlogWeb/blog/templates/blog/page_not_found.html
{% extends 'main/base.html' %}

{% block contant %}

<div class="nopage-contauner">
    <h2>This post not found</h2>
    <a type="button" class="btn btn-secondary" href="{% url 'main:home_views'%}"><h3>back To Hom </h3></a>
</div>
 



{%endblock%}

BlogWeb/blog/templates/blog/search.html
{% extends 'main/base.html' %}

{% block contant %}
<div class="container-home-add">

    <h1>ALL POST</h1>
    <h1>Search results for "{{request.GET.search}}"</h1>

    <div class="row">

        {% for blog in blogs %}

            <div class="col-5">
                <div class="d-flex flex-column gap-2 p-3 border border-1 rounded-4 shadow mb-4 text-bg-secondary p-3">

                    <a href="{% url 'blog:details_blog_views' blog.id %}"><h3>{{ blog.title }}</h3></a> 
                    <img width="500px" height="200px"  src="{{blog.image.url}}" />
                    <h4>{{blog.content}}</h4>
                    <h4> is published :{{ blog.is_published }} </h4>
                    <h4>  "{{blog.category}}"</h4>
                    <h4>published at {{blog.published_at}}</h4>
                   
                    
                    

                </div>
            </div>
            


        {% endfor %}

    </div>

</div>

{%endblock%}

BlogWeb/blog/templates/blog/updated_blog.html
{% extends 'main/base.html' %}

{% block contant %}

<div class="container-add">
    <h1>Update {{blogs.title}}:</h1>
    <br>
    <div class="row">
        <div class="col-8">
            <form action="{% url 'blog:updated_blog' blogs.id %}"method="post">
                {% csrf_token %}
                <label>Title blog: </label>
                <input  class="form-control" type="text" name="title" placeholder="Enter bolg title ">
            <br>
            <label>Content: </label>
            <textarea name="content"></textarea>
            <br>
            <br>
            <label>is published </label>
            <select name="is_published"  class="form-control">
                <option value="True"> yes</option>
                <option value="False"> no</option>
            </select>
           <br>
           <label>Category</label>
           {% for key , value in categories.choices %}
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="category" id="{{key}}" value="{{value}}">
                    <label class="form-check-label" for="{{key}}">
                       {{value}}
                    </label>
                </div>
            {% endfor %}

            <button  class="form-control" type="submit">Update </button>


            </form>

        </div>
    </div>
</div>



{%endblock%}