myBolg/blog/urls.py
from django.urls import path
from . import views
app_name = "blog"

urlpatterns = [
    path("add/", views.addBlog, name="addBlog"),
    path("all/", views.displayBlog, name="displayBlog"),
    path("details/<blog_id>/", views.detailsBlog, name="detailsBlog"),
    path("update/<blog_id>/", views.updateBlog, name="updateBlog"),
    path("delete/<blog_id>/", views.deleteBLog, name="deleteBlog"),
    path("search/", views.searchBlog, name="searchBlog"),


    
]

myBolg/main/urls.py
from django.urls import path
from . import views
app_name = "main"

urlpatterns = [
    path("", views.homePage, name="homePage"),
    
]

myBolg/myBolg/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
    path('blogs/', include("blog.urls")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myBolg/blog/models.py
from django.db import models

class Blog(models.Model):
    categories = models.TextChoices("Categories",["Food","Travel" , "Art" , "News"])

    title = models.CharField(max_length=2048)
    content = models.TextField()
    is_published = models.BooleanField()
    published_at = models.DateTimeField()
    category = models.CharField(max_length=2048,choices=categories.choices , default="Art")
    image = models.ImageField(upload_to="image/" , default="image/default.jpg")
    

myBolg/blog/views.py
from django.shortcuts import render , redirect
from django.http import HttpRequest, HttpResponse
from .models import Blog


def addBlog(request : HttpRequest):

    if request.method == "POST":
        
        newBlog = Blog(title = request.POST["title"] , content = request.POST["content"] ,is_published=  request.POST["is_published"] , published_at = request.POST["published_at"] , category = request.POST["category"] , image = request.FILES["image"])
        newBlog.save()
        return redirect("blog:displayBlog")

    return render(request, "blog/addBlog.html" , {"categories" : Blog.categories})


def displayBlog(request : HttpRequest):

    if "category" in request.GET and request.GET["category"] =="Food":
      blogs = Blog.objects.filter(category__contains ="Food")

    elif "category" in request.GET and request.GET["category"] =="Travel":
        blogs = Blog.objects.filter(category__contains ="Travel")

    elif "category" in request.GET and request.GET["category"] =="Art":
        blogs = Blog.objects.filter(category__contains ="Art")
        
    elif "category" in request.GET and request.GET["category"] =="News":
        blogs = Blog.objects.filter(category__contains ="News")
    else:
        blogs = Blog.objects.all()
    return render(request ,"blog/display.html" , {"blogs" : blogs})

def detailsBlog(request : HttpRequest ,blog_id):
    try: 
       blog = Blog.objects.get(id = blog_id)
       
    except  Exception as e:

       return render(request, "main/not_found.html")
       
    return render(request ,"blog/details.html" , {"blog" : blog})

def updateBlog(request : HttpRequest , blog_id):
    try:
            blog = Blog.objects.get(id = blog_id)

            if request.method == "POST":
                blog.title = request.POST["title"]
                blog.content = request.POST["content"]
                blog.is_published=  request.POST["is_published"]
                blog.published_at = request.POST["published_at"]
                blog.category = request.POST["category"]
                blog.image = request.FILES["image"]
                blog.save()

                return redirect( "blog:detailsBlog" , blog_id = blog.id)
    
           
            return render(request ,"blog/update.html" , {"blog" : blog , "categories" : Blog.categories})                    
    except  Exception as e:

       return render(request, "main/not_found.html")
    
    
   

def deleteBLog(request : HttpRequest , blog_id):
     try:
        blog = Blog.objects.get(id = blog_id)
        blog.delete()

        return redirect("blog:displayBlog")
     except  Exception as e:

       return render(request, "main/not_found.html")
       
def searchBlog(request : HttpRequest):
   if "search" in request.GET:
      titleSearch = request.GET["search"]
      blogs = Blog.objects.filter(title__contains= titleSearch)
   else:
      blogs = Blog.objects.all() 

   return render(request, "blog/search.html" ,  {"blogs" : blogs}) 
    

myBolg/main/views.py
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse

def homePage(request : HttpRequest):

    return render(request ,"main/home.html")

myBolg/blog/templates/blog/addBlog.html
{% extends 'main/base.html' %}

{% block title %} Add post {% endblock %}

{% block content %}
<div class = "form">
<section class="container content">

    <h1>Add new post</h1>

    <div class="row">

        <div class="col-6">
           

            <form action="{% url 'blog:addBlog' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <label>Post Title:</label>
                <input class="form-control mt-3" type="text" name="title"  />

                <label>Post Content:</label>
                <textarea class="form-control mt-3" name="content"></textarea>

                <label>Has it been published?:</label>
                <select name="is_published" class="form-select mt-3">
                    <option value="True">yes</option>
                    <option value="False">no</option>     
                </select>
                 
                {% for key, value in categories.choices %}
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="category" id="{{key}}" value="{{value}}">
                        <label class="form-check-label" for="{{key}}">
                        {{value}}
                        </label>
                    </div>
                {% endfor %}
                <label>published time:</label>
                <input class="form-control mt-3" name="published_at" type="datetime-local" />
                
                <label>Post Image:</label>
                <input type="file" name="image"  class="form-control" accept="image/*"/>

                <input class="btn btn-dark mt-3" type="submit" value="Create Post" />
            </form>

        </div>

    </div>

</section>
</div>
{% endblock %}

myBolg/blog/templates/blog/details.html
{% extends 'main/base.html' %}

{% block title %} {{blog.title}} {% endblock %}

{% block content %}
<div class = "form">
<section class="container  content ">

    <h1 class = "text-uppercase fw-bold fs-1 text-center">Details Post</h1>

    
        <table class="table mb-3">
            <thead>
              <tr>
                <th scope="col">Title</th>
                <th scope="col">Content</th>
                <th scope="col">Publish status</th>
                <th scope="col">Category</th>
                <th scope="col"> Published Time </th>
                <th scope="col"> Image </th>
              </tr>
            </thead>
     

            <div class="col-6 ">
         

                <tbody>
                  <tr>
                   
                    <td> {{ blog.title }}</td>
                    <td>{{blog.content}}</td>
                    <td> {{ blog.is_published }}</td>
                    <td> {{ blog.category }}</td>
                    <td> {{ blog.published_at }}</td>
                    <td><img width="70px" height="70px" src="{{blog.image.url}}" /></td>
                  </tr>
                  </tbody>
            </div>
               
        </table>
    <div class="dropdown">
        <button class="btn btn-primary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
          Edit
        </button>
        <ul class="dropdown-menu ">
          <li><a class="dropdown-item" href="{% url 'blog:updateBlog' blog.id %}">Update</a></li>
          <li><a class="dropdown-item" href="{% url 'blog:deleteBlog' blog.id %}">Delete</a></li>
        </ul>
      </div>
</section>
</div>


{% endblock %}

myBolg/blog/templates/blog/display.html
{% extends 'main/base.html' %}

{% block title %} Display Posts {% endblock %}

{% block content %}
<div class = "form">
<section class="container  content ">

    <h1 class = "text-uppercase fw-bold fs-1 text-center">All Posts</h1>

   
        <table class="table">
            <thead>
              <tr>
                <a href=""><th scope="col">Title</th></a> 
                <th scope="col">Content</th>
                <th scope="col">Publish status</th>
                <th scope="col">Category</th>
                <th scope="col"> Published Time </th>
                <th scope="col"> Image </th>
              </tr>
            </thead>
            <div class="dropdown mb-3 d-flex justify-content-between ">
              <button class="btn btn-primary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                Category
              </button>
              <ul class="dropdown-menu ">
                <li><a class="dropdown-item" href="{% url 'blog:displayBlog' %}?category=Food">Food</a></li>
                <li><a class="dropdown-item" href="{% url 'blog:displayBlog' %}?category=Travel">Travel</a></li>
                <li><a class="dropdown-item" href="{% url 'blog:displayBlog' %}?category=Art">Art</a></li>
                <li><a class="dropdown-item" href="{% url 'blog:displayBlog' %}?category=News">News</a></li>
              </ul>
             
            </div>
        {% for blog in blogs %}

            <div class="col-6 ">
         

                <tbody>
                  <tr>
                   
                    <td><a href="{% url 'blog:detailsBlog' blog.id %}">{{ blog.title }}</a></td>
                    <td>{{blog.content}}</td>
                    <td> {{ blog.is_published }}</td>
                    <td> {{ blog.category }}</td>
                    <td> {{ blog.published_at }}</td>
                    <td><img width="70px" height="70px" src="{{blog.image.url}}" /></td>
                  </tr>
                  </tbody>
                  
            </div>
              


        {% endfor %}

    </table>

</section>
</div>


{% endblock %}

myBolg/blog/templates/blog/search.html
{% extends 'main/base.html' %}

{% block title %} Search Posts {% endblock %}

{% block content %}
<div class = "form">
<section class="container  content ">

    <h1 class = "text-uppercase fw-bold fs-1 text-center">Search results for "{{ request.GET.search }}"</h1>

   
        <table class="table">
            <thead>
              <tr>
                <a href=""><th scope="col">Title</th></a> 
                <th scope="col">Content</th>
                <th scope="col">Publish status</th>
                <th scope="col">Category</th>
                <th scope="col"> Published Time </th>
                <th scope="col"> Image </th>
              </tr>
            </thead>
            <div class="dropdown mb-3 d-flex justify-content-between ">
              <button class="btn btn-primary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                Category
              </button>
              <ul class="dropdown-menu ">
                <li><a class="dropdown-item" href="{% url 'blog:displayBlog' %}?category=Food">Food</a></li>
                <li><a class="dropdown-item" href="{% url 'blog:displayBlog' %}?category=Travel">Travel</a></li>
                <li><a class="dropdown-item" href="{% url 'blog:displayBlog' %}?category=Art">Art</a></li>
                <li><a class="dropdown-item" href="{% url 'blog:displayBlog' %}?category=News">News</a></li>
              </ul>
             
            </div>
        {% for blog in blogs %}

            <div class="col-6 ">
         

                <tbody>
                  <tr>
                   
                    <td><a href="{% url 'blog:detailsBlog' blog.id %}">{{ blog.title }}</a></td>
                    <td>{{blog.content}}</td>
                    <td> {{ blog.is_published }}</td>
                    <td> {{ blog.category }}</td>
                    <td> {{ blog.published_at }}</td>
                    <td><img width="70px" height="70px" src="{{blog.image.url}}" /></td>
                  </tr>
                  </tbody>
                  
            </div>
              


        {% endfor %}

    </table>

</section>
</div>


{% endblock %}

myBolg/blog/templates/blog/update.html
{% extends 'main/base.html' %}

{% block title %} Update {{ blog.title }} {% endblock %}

{% block content %}
<div class = "form">
<section class="container content">

    <h1>update {{ blog.title }}</h1>

    <div class="row">

        <div class="col-6">
           

            <form action="{% url 'blog:updateBlog' blog.id %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <label>Post Title:</label>
                <input class="form-control mt-3" type="text" name="title" value = "{{ blog.title }}" />

                <label>Post Content:</label>
                <textarea class="form-control mt-3" name="content">{{blog.content}}</textarea>

                <label>Has it been published?:</label>
                <select name="is_published" class="form-select mt-3">
                    <option value="True" {% if blog.is_published == True %} selected {% endif %}>yes</option>
                    <option value="False" {% if blog.is_published  == False %} selected {% endif %}>no</option>     
                </select>
             
                <label>Category post:</label>
                {% for key, value in categories.choices %}
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="category" id="{{key}}" value="{{key}}" {% if blog.category == key %} checked {% endif %}>
                        <label class="form-check-label" for="{{key}}">
                        {{value}}
                        </label>
                    </div>
                {% endfor %}
                <label>published time:</label>
                <input class="form-control mt-3" name="published_at" type="datetime-local"  value = "{{blog.published_at | date:'Y-m-d'}} {{ blog.published_at|time:'H:i' }}"/>
             
                <label>Post Image:</label>
                <input type="file" name="image"  class="form-control" accept="image/*"/>

                <input class="btn btn-dark mt-3" type="submit" value="Update Post" />
            </form>

        </div>

    </div>

</section>
</div>
{% endblock %}

myBolg/main/templates/main/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="/static/css/main.css" rel="stylesheet" />
    <title>{% block title %} {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>
  <body>
    <div class="container">
        <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
          <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
            <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
            <span class="fs-4">Blog</span>
          </a>
    
          <ul class="nav nav-pills">
            <li class="nav-item"><a href="{% url 'main:homePage' %}" class="nav-link active" aria-current="page">Home</a></li>
            <li class="nav-item"><a href="{% url 'blog:addBlog' %}" class="nav-link">Add Blog</a></li>
            <li class="nav-item"><a href="{% url 'blog:displayBlog' %}" class="nav-link">Dicover Blogs</a></li>
            <li class="nav-item"><a href="{% url 'blog:searchBlog' %}" class="nav-link">Search Page</a></li>
        </ul>
        <form role="search" action="{% url 'blog:searchBlog'  %}" method="GET">
    
          <input type="search" name = "search" placeholder="Search" class="form-control ms-3 me-3"aria-label="Search"/>
         
        </form>
        
        </header>
      </div>

      {% block content %}

      {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

myBolg/main/templates/main/home.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}BLog{% endblock %}


{% block content  %}
<div class = "form">
<div class = "container content">
    <div class = "row pb-5">
        <h1 class = "text-uppercase fw-bold fs-1 text-center">Welcome to blog Website</h1>
    </div>
   
        <div class = "button">
            <a href="{% url 'blog:addBlog' %}" class="btn btn-dark text-center ">ADD POST</a>
              
        </div>
        <div class = "button2">
            
            <a href="{% url 'blog:displayBlog' %}" class="btn btn-dark text-center  ">DISPLAY POSTS</a>
        </div>
        

    
   

</div>
</div>
{% endblock %}

myBolg/main/templates/main/not_found.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}BLog{% endblock %}


{% block content  %}
<div class = "form">
<div class = "container content">
    <div class = "row pb-5">
        <h1 class = "text-uppercase fw-bold fs-1 text-center">Page Does not Exit</h1>
    </div>
   
        <div class = "button">
            <a href="{% url 'blog:displayBlog' %}" class="btn btn-dark ms-1">Display Page</a>
              
        </div>
        

    
   

</div>
</div>
{% endblock %}