Blog/Blog/urls.py
from django.contrib import admin
from django.urls import path ,include
from . import settings #we use setting model in setting.py , so we import it
from django.conf.urls.static import static # to use setting media root and urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
    path('index/', include("index.urls")),
    path('accounts/',include("accounts.urls")),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Blog/blogs/urls.py
from django.urls import path
from . import views
app_name = "blogs"
urlpatterns = [
    path('read/',views.read,name='read'),
    path('add/',views.add,name='add'),
    path("detail/<blog_id>/", views.detail, name="detail"),
    path("update/<blog_id>/", views.update, name="update"),
    path("delete/<blog_id>", views.delete, name="delete"),
    path('search/',views.search,name='search'),
    path("all/", views.BlogsCat, name="BlogsCat"),
    
]

Blog/lapblog/urls.py
from django.urls import path
from . import views

app_name = "lapblog"

urlpatterns = [ 
    path("add/", views.add_blog_view, name="add_blog_view"),
    path("", views.blog_home_view, name="blog_home_view"),
    path("detail/<blog_id>/", views.blog_detail_view, name="blog_detail_view"),
    path("update/<blog_id>/", views.update_blog_view, name="update_blog_view"),
    path("delete/<blog_id>", views.delete_blog_view, name="delete_blog_view"),
    path("search", views.search_blog_view, name="search_blog_view"),
    path("category/<cat>/", views.blog_home_view_cat, name="blog_home_view_cat")

  ]

Blog/blogs/models.py
from django.db import models


class Blog(models.Model):
    
    categories=models.TextChoices("Categories", ["Makeup", "Movie","Celebrities", "Care","Places"])
  

    title=models.CharField(max_length=100)
    content=models.TextField()
    is_published=models.BooleanField()
    published_at=models.DateField()
    category=models.CharField(max_length=50,choices=categories.choices, default="Movie")
    poster = models.ImageField(upload_to="images/", default="images/blog.jpg")

Blog/blogs/views.py
from django.shortcuts import render ,redirect
from django.http import HttpRequest, HttpResponse
from .models import Blog



def read(request : HttpRequest):

    blogs=Blog.objects.all()

    return render(request, "blogs/read.html", {"blogs" : blogs})




def add(request : HttpRequest):
    if request.method=="POST":
        new_blog=Blog(title=request.POST['title'],content=request.POST['content'],is_published=request.POST['is_published'],published_at=request.POST['published_at'],category=request.POST['category'], poster=request.FILES['poster'])
        
        new_blog.save()
        return redirect("blogs:read")
    
    return render(request,'blogs/add.html', {"categories" : Blog.categories})


def detail(request:HttpRequest, blog_id):

    blog = Blog.objects.get(id=blog_id)

    return render(request, "blogs/detail.html", {"blog" : blog})



def update(request : HttpRequest,blog_id):
    blog=Blog.objects.get(id=blog_id)
    if request.method=="POST":
        blog.title=request.POST['title']
        blog.content=request.POST['content']
        blog.is_published=request.POST['is_published']
        blog.published_at= request.POST["published_at"]
        blog.category=request.POST['category']
        blog.save()
        return redirect('blogs:detail',blog_id=blog.id)
    return render(request,'blogs/update.html',{"blog" : blog,'categories':Blog.categories})


def delete(request: HttpRequest, blog_id):

    blog = Blog.objects.get(id=blog_id)
    blog.delete()

    return redirect("blogs:read")


def search(request: HttpRequest):
    if 'search' in request.GET:
        query = request.GET['search']
        blogs = Blog.objects.filter(title__contains=query)
    else:
         blogs = Blog.objects.all()   
    return render(request, 'blogs/search.html',  {"blogs" : blogs})




def BlogsCat(request : HttpRequest):

    if "category" in request.GET and request.GET["category"] =="Makeup":
      blogs = Blog.objects.filter(category__contains ="Makeup")

    elif "category" in request.GET and request.GET["category"] =="Movie":
        blogs = Blog.objects.filter(category__contains ="Movie")

    elif "category" in request.GET and request.GET["category"] =="Celebrities":
        blogs = Blog.objects.filter(category__contains ="Celebrities")

    elif "category" in request.GET and request.GET["category"] =="Care":
        blogs = Blog.objects.filter(category__contains ="Care")

    elif "category" in request.GET and request.GET["category"] =="Places":
        blogs = Blog.objects.filter(category__contains ="Places")    
    else:
        blogs = Blog.objects.all()
    return render(request ,"blogs/read.html" , {"blogs" : blogs})

Blog/blogs/templates/blogs/add.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %}Add blog{% endblock %}
{% block content %}
<section class="container">

    <h1>Add new blog</h1>

    <div class="row">

        <div class="col-6">
            <form action="{% url 'blogs:add' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <label>blog :</label>
                <input class="form-control" type="text" name="title" placeholder="title Name" />

                <label>Content:</label>
                <textarea class="form-control" name="content"></textarea>

                <label>is_published:</label>
                <select name="is_published" class="form-select">
                    <option value="True">True</option>
                    <option value="False">False</option>
                
                </select>

                <label>Category</label>

                {% for key, value in categories.choices %}
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="category" id="{{key}}" value="{{value}}">
                        <label class="form-check-label" for="{{key}}">
                        {{value}}
                        </label>
                    </div>
                {% endfor %}
                
                <label>Blog Images:</label>
                <input class="form-control" name="poster" type="file" accept="image/*"/>
                
                <label>Published at:</label>
                <input class="form-control" name="published_at" type="date" />
            

                <input class="btn btn-primary" type="submit" value="Create blog" />
            </form>

        </div>

    </div>

</section>
{% endblock %}

Blog/blogs/templates/blogs/detail.html
{% extends 'main/base.html' %}

{% block title %} {{ blog.titel }} {% endblock %}

{% block content %}

<section class="container row m-4 p-4">
        <div class="row ">
            <div class="col">
            <div class="d-flex flex-column gap-2">
            <h2>Title: {{ blog.title }}</h2>
            <h4>Content: <br>{{ blog.content }}</h4>
            <h4>is published: {{ blog.is_published }}</h4>
            <h4>published at: {{ blog.published_at }}</h4>
            <h4>category: {{blog.category}}</h4>
            <div class="row">
            <div class="dropdown">
                <button class="btn btn-primary dropdown-toggle col-3" type="button" data-bs-toggle="dropdown" aria-expanded="false">Edit</button>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{% url 'blogs:update' blog.id %}">Update</a></li>
                  <li><a class="dropdown-item" href="{% url 'blogs:delete' blog.id %}">Delete</a></li>
                </ul>
              </div>
              <a href="{% url 'blogs:read'%}"><button type="button" class="btn btn-primary col-3 mt-3"> all blogs</button></a>
            </div>
          </div>
            </div>
        </div>
</section>



{% endblock %}

Blog/blogs/templates/blogs/not_found.html
{% extends 'main/base.html' %}
{% load static %}
{% block title%} sorry {%endblock%}

{% block content %}
<section class="container"> 
    <div class="row">
<h1> Sorry can not found</h1>
    </div>
    </section>

{% endblock %}

Blog/blogs/templates/blogs/read.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %}Read blog{% endblock %}
{% block content %}

<section class="container">
    <div class="d-flex justify-content-between">
        <h1 class="text-center">All blogs</h1>
        <br>

        <div class="dropdown">
            <button class="btn btn-primary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
              Order By
            </button>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'blogs:read' %}">Latest</a></li>
              <li><a class="dropdown-item" href="{% url 'blogs:read' %}?order=top">Rating</a></li>
            </ul>
          </div>
        </div>
        <div class="dropdown mb-3 d-flex justify-content-between ">
            <button class="btn btn-primary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
              Category
            </button>
            <ul class="dropdown-menu ">
              <li><a class="dropdown-item" href="{% url 'blogs:BlogsCat' %}?category=Makeup">Makeup</a></li>
              <li><a class="dropdown-item" href="{% url 'blogs:BlogsCat' %}?category=Movie">Movie</a></li>
              <li><a class="dropdown-item" href="{% url 'blogs:BlogsCat' %}?category=Celebrities">Celebrities</a></li>
              <li><a class="dropdown-item" href="{% url 'blogs:BlogsCat' %}?category=Care">Care</a></li>
              <li><a class="dropdown-item" href="{% url 'blogs:BlogsCat' %}?category=Places">Places</a></li>

            </ul>

          </div>
    <div class="row">

        {% for blog in blogs %}

            <div class="mt-4 col-4">

                <div class="d-flex flex-column gap-2 p-3 border border-1 rounded-4 shadow">
                    <img src="{{blog.poster.url}}" width="100%" height="300" />
                    <a href="{% url 'blogs:detail'  blog.id %}"><h4>Title: {{blog.title}}</h4></a>
                    <h5>Content: {{blog.content}}</h5>
                    <h5>is published: {{blog.is_published}} </h5>
                    <h5>published at: {{blog.published_at}}</h5>
                </div>

            </div>

        {% endfor %}

    </div>

</section>


{% endblock %}

Blog/blogs/templates/blogs/search.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %}Read blog{% endblock %}
{% block content %}

<section class="container">
    <div class="d-flex justify-content-between">
    <h1 class = "text-uppercase fw-bold fs-1 text-center">Search results for "{{ request.GET.search }}"</h1>
    <br>
        

        <div class="dropdown">
            <button class="btn btn-primary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
              Order By
            </button>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'blogs:read' %}">Latest</a></li>
              <li><a class="dropdown-item" href="{% url 'blogs:read' %}?order=top">Rating</a></li>
            </ul>
          </div>
        </div>
        <div class="dropdown mb-3 d-flex justify-content-between ">
            <button class="btn btn-primary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
              Category
            </button>
            <ul class="dropdown-menu ">
              <li><a class="dropdown-item" href="{% url 'blogs:BlogsCat' %}?category=Makeup">Makeup</a></li>
              <li><a class="dropdown-item" href="{% url 'blogs:BlogsCat' %}?category=Movie">Movie</a></li>
              <li><a class="dropdown-item" href="{% url 'blogs:BlogsCat' %}?category=Celebrities">Celebrities</a></li>
              <li><a class="dropdown-item" href="{% url 'blogs:BlogsCat' %}?category=Care">Care</a></li>
              <li><a class="dropdown-item" href="{% url 'blogs:BlogsCat' %}?category=Places">Places</a></li>

            </ul>

          </div>
    <div class="row">

        {% for blog in blogs %}

            <div class="mt-4 col-4">

                <div class="d-flex flex-column gap-2 p-3 border border-1 rounded-4 shadow">
                    <img src="{{blog.poster.url}}" width="100%" height="300" />
                    <a href="{% url 'blogs:detail'  blog.id %}"><h4>Title: {{blog.title}}</h4></a>
                    <h5>Content: {{blog.content}}</h5>
                    <h5>is published: {{blog.is_published}} </h5>
                    <h5>published at: {{blog.published_at}}</h5>
                </div>

            </div>

        {% endfor %}

    </div>
</section>



{% endblock %}

Blog/blogs/templates/blogs/show_blogs.html
{% extends 'main/base.html' %}
{% block title%} show blogs {%endblock%}


{% block content %}

<section class="container">

    <h1>All Blogs </h1>

    <div class="row">

        {% for blog in blogs %}
            {% if blog.is_published  == True %}

                <div class="col-10 m-2">
                    <div class="d-flex flex-column gap-2 p-3 border border-1 rounded-4 shadow">
                        <img src="{{blog.poster.url}}" />
                        <span class="cat ps-3 pe-3 rounded-pill text-black {{blog.category}}"><a class="text-decoration-none text-black" href="{% url 'blogs:blogs_home_view_cat' blog.category %}">{{blog.category}}</a></span>
                        <a href="{% url 'blogs:blog_detail_view' blog.id %}"><h2>{{ blog.title }}</h2></a>
                    </div>
                    <div class="d-flex gap-1">
                    </div>

                </div>
            {% endif %}


        {% endfor %}

    </div>

</section>

{% endblock %}

Blog/blogs/templates/blogs/update.html
{% extends 'main/base.html' %}


{% block title %} Update {{ blog.titel }}{% endblock %}


{% block content %}
    <div class="container mt-5"> 

        <div class="row">
            <h2>Update {{blog.title}}:</h2>
            <div class="col">

                <form action="{% url 'blogs:update' blog.id %}" method="POST" enctype="multipart/form-data">

                    {% csrf_token %}
                <label>blog name:</label>
                <input class="form-control" type="text" name="title" placeholder="blog titel" value="{{blog.titel}}" />

                <label>blog content:</label>
                <textarea class="form-control" name="content">{{blog.Content}}</textarea>

                <label>is published:</label>
                <select name="is_published" class="form-select">
                    <option value="True"  {% if blog.is_published == True %} selected {% endif %}>True</option>
                    <option value="False"{% if blog.is_published == False %} selected {% endif %} >False</option>
                
                </select>
                <label>Category:</label>
                {% for key, value in categories.choices %}
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="category" id="{{key}}" value="{{key}}" {% if blog.category == key %} checked {% endif %}>
                        <label class="form-check-label" for="{{key}}">
                        {{value}}
                        </label>
                    </div>
                {% endfor %}

                <label>Published at:</label>
                <input class="form-control" name="published_at" type="date" value="{{blog.published_at|date:'Y-m-d' }}"/>
                

                <input class="btn btn-primary mt-2" type="submit" value="Update Blog" />
            

                </form>

            </div>
        </div>

    </div>
    
{% endblock %}